# Jekyll Resume Theme

# Site settings
title: Tai
email: email@domain.com
description: I'm Xue.
baseurl: ""
url: "http://atai.me"
name: Xue XingTai
job: Master of Physics
location: Peking, China
languages: Optical Information Science and Technology
twitter_username: 
github_username:  xuexingtai
codepen_username:  
email_address: 584800354@qq.com

# Build settings
markdown: kramdown
